version: 2
jobs:
  build:
    working_repositories: ~/repositories
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: v1-deps-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: Setup SSH for AWS CodeCommit
          command: |
            chmod +x scripts/setup-ssh.sh
            scripts/setup-ssh.sh $SSH_KEY_ID $AWS_DEFAULT_REGION
      - run:
          name: Mirror Github Repositories to AWS CodeCommit
          command: pipenv run python3 src/github-aws-commit-mirror.py

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *" # Trigger every night at 11pm
          filters:
            branches:
              only:
                - master