version: 2
jobs:
  build:
    working_repositories: ~/repositories
    docker:
      - image: circleci/python:3.8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ff:eb:19:05:10:d8:62:a2:33:07:b0:6f:1d:d7:0f:cf"
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv 
            pipenv install
      - save_cache:
          key: v1-deps-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: Mirroring process
          command: |
            pipenv run python3 src/github-aws-commit-mirror.py
            ls -ltra