version: 2
jobs:
  build:
    working_repositories: ~/repositories
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install Dependencies
          command: |
            sudo pip install pipenv 
            pipenv install
      - save_cache:
          key: v1-deps-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          name: Mirroring process
          command: |
            ls -ltra
            pipenv run python3 src/github-aws-commit-mirror.py