# This is a basic workflow to help you get started with Actions

name: Mirroring

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "mirroring"
  mirroring:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ssh://git-codecommit.eu-central-1.amazonaws.com/v1/repos/github-aws-commit-mirror
        ssh_private_key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        ssh_username: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }} # <-- (for codecommit) you need to specify ssh-key-id as ssh username.
