name: Mirroring
on: [push, delete]
jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ssh://git-codecommit.eu-central-1.amazonaws.com/v1/repos/github-aws-commit-mirror
        ssh_private_key: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        ssh_username: ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}
